/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */




/*
 *  Math1.java
 * 
 *  Rev 1
 *
 *  19/04/2013
*
 * @author Aidan Durnin, x12388721
 *
*/
public class Math1 extends javax.swing.JFrame {

    /**
     * Creates new form Math1
     */
    public Math1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bkgrd = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        maintxt = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        workshop = new javax.swing.JButton();
        b2home = new javax.swing.JButton();
        examfocused = new javax.swing.JButton();
        contact = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bkgrd.setBackground(new java.awt.Color(255, 255, 255));

        header.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        header.setText("NCI MATH SUPPORT");

        maintxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextPane1.setText("   Welcome to the NCI Math Support page!\nHere you can find all you need to know about\n  the different types of support that NCI offer\n                              in maths.\n    Click below to have a look at what we offer. ");
        maintxt.setViewportView(jTextPane1);

        workshop.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        workshop.setText("Math Workshop");
        workshop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workshopActionPerformed(evt);
            }
        });

        b2home.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b2home.setText("Back to Home");
        b2home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2homeActionPerformed(evt);
            }
        });

        examfocused.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        examfocused.setText("Exam Focused");
        examfocused.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examfocusedActionPerformed(evt);
            }
        });

        contact.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        contact.setText("Contact");
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bkgrdLayout = new javax.swing.GroupLayout(bkgrd);
        bkgrd.setLayout(bkgrdLayout);
        bkgrdLayout.setHorizontalGroup(
            bkgrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bkgrdLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(header)
                .addGap(76, 76, 76))
            .addGroup(bkgrdLayout.createSequentialGroup()
                .addGroup(bkgrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bkgrdLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(maintxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bkgrdLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(bkgrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b2home, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(workshop, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(bkgrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(examfocused, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        bkgrdLayout.setVerticalGroup(
            bkgrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkgrdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header)
                .addGap(18, 18, 18)
                .addComponent(maintxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bkgrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workshop, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(examfocused, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bkgrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b2home, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkgrd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkgrd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void workshopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workshopActionPerformed
        // TODO add your handling code here:
        new Math2().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_workshopActionPerformed

    private void examfocusedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examfocusedActionPerformed
        // TODO add your handling code here:
        new Math3().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_examfocusedActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
        new Math4().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_contactActionPerformed

    private void b2homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2homeActionPerformed
        // TODO add your handling code here:
        new Welcome2().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_b2homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Math1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Math1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Math1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Math1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Math1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b2home;
    private javax.swing.JPanel bkgrd;
    private javax.swing.JButton contact;
    private javax.swing.JButton examfocused;
    private javax.swing.JLabel header;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JScrollPane maintxt;
    private javax.swing.JButton workshop;
    // End of variables declaration//GEN-END:variables
}
