/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/*
 *  Math4.java
 * 
 *  Rev 1
 *
 *  19/04/2013
 *
 * @author Aidan Durnin, x12388721
 *
 */
public class Math4 extends javax.swing.JFrame {

    /**
     * Creates new form Math4
     */
    public Math4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bkg = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        b2maths = new javax.swing.JButton();
        mainText = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        phone = new javax.swing.JLabel();
        email = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bkg.setBackground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setText("Contact");

        b2maths.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b2maths.setText("Back to Maths");
        b2maths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2mathsActionPerformed(evt);
            }
        });

        jTextPane2.setEditable(false);
        jTextPane2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane2.setText("  \nYou can contact Jonathan Lambert the Mathematics Development \n               and Support Officer through a number of ways:\n");
        mainText.setViewportView(jTextPane2);

        phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phone.setText("<html>\n<b>        Phone:</b>   <&nbsp    01-4498650\n</html>");

        email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email.setText("<html>\n\n<b>E-Mail:</b> <&nbsp   jonathan.lambert@ncirl.ie\n</html>");

        javax.swing.GroupLayout bkgLayout = new javax.swing.GroupLayout(bkg);
        bkg.setLayout(bkgLayout);
        bkgLayout.setHorizontalGroup(
            bkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkgLayout.createSequentialGroup()
                .addGroup(bkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bkgLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(title))
                    .addGroup(bkgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(b2maths))
                    .addGroup(bkgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mainText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bkgLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bkgLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bkgLayout.setVerticalGroup(
            bkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(b2maths, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b2mathsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2mathsActionPerformed
        // TODO add your handling code here:
        new Math1().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_b2mathsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Math4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Math4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Math4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Math4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b2maths;
    private javax.swing.JPanel bkg;
    private javax.swing.JLabel email;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JScrollPane mainText;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

          


}
