/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.ButtonGroup;



/*
 *  Math2.java
 * 
 *  Rev 1
 *
 *  19/04/2013
 *
 * @author Aidan Durnin, x12388721
 *
 */
public class Math2 extends javax.swing.JFrame {

    /**
     * Creates new form Math2
     */
    public Math2() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bkg = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        b2maths = new javax.swing.JButton();
        bahahr1 = new javax.swing.JButton();
        hcbs2 = new javax.swing.JButton();
        bamtb1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bkg.setBackground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setText("Math Workshop");

        text.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        text.setText("What class are you in?");

        b2maths.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b2maths.setText("Back to Maths");
        b2maths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2mathsActionPerformed(evt);
            }
        });

        bahahr1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bahahr1.setText("BAHAHR1");
        bahahr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bahahr1ActionPerformed(evt);
            }
        });

        hcbs2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hcbs2.setText("HCBS2");
        hcbs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hcbs2ActionPerformed(evt);
            }
        });

        bamtb1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bamtb1.setText("BAMTB1");
        bamtb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bamtb1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bkgLayout = new javax.swing.GroupLayout(bkg);
        bkg.setLayout(bkgLayout);
        bkgLayout.setHorizontalGroup(
            bkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkgLayout.createSequentialGroup()
                .addGroup(bkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bkgLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(title))
                    .addGroup(bkgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(b2maths))
                    .addGroup(bkgLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(bkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bamtb1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bahahr1)
                            .addComponent(text)
                            .addComponent(hcbs2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        bkgLayout.setVerticalGroup(
            bkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text)
                .addGap(18, 18, 18)
                .addComponent(bahahr1)
                .addGap(18, 18, 18)
                .addComponent(hcbs2)
                .addGap(18, 18, 18)
                .addComponent(bamtb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(b2maths, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b2mathsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2mathsActionPerformed
        // TODO add your handling code here:
        new Math1().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_b2mathsActionPerformed

    private void bahahr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bahahr1ActionPerformed
        // TODO add your handling code here:
        new Math21().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bahahr1ActionPerformed

    private void hcbs2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hcbs2ActionPerformed
        // TODO add your handling code here:
        new Math22().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_hcbs2ActionPerformed

    private void bamtb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bamtb1ActionPerformed
        // TODO add your handling code here:
        new Math23().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bamtb1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Math2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Math2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Math2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Math2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Math2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b2maths;
    private javax.swing.JButton bahahr1;
    private javax.swing.JButton bamtb1;
    private javax.swing.JPanel bkg;
    private javax.swing.JButton hcbs2;
    private javax.swing.JLabel text;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables






}
