/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

//import computing.support.SentFormPopUP;
import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;



/*
 *  Math3.java
 * 
 *  Rev 1
 *
 *  19/04/2013
 *
 * @author Aidan Durnin, x12388721
 *
 */
public class Math3 extends javax.swing.JFrame {

    private ArrayList<Query> aList;
    private String query;
    /**
     * Creates new form Math3
     */
    public Math3() {
        initComponents();
        aList = new ArrayList<>();
        query = new String();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bkgd = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        maintxt = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        backBtn = new javax.swing.JButton();
        subBtn = new javax.swing.JButton();
        seeBtn = new javax.swing.JButton();
        queryBox = new javax.swing.JScrollPane();
        queryTF = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bkgd.setBackground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setText("Exam Focused");

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane1.setText("   NCI offers constantly updating Exam support \n throughout the school year and during holidays \n             for exams and repeat exams. \n    To find out the latest information you can \n      leave a query below with your student \n        number and we will get back to go.");
        maintxt.setViewportView(jTextPane1);

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backBtn.setText("Back to Maths");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        subBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        subBtn.setText("Submit");
        subBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtnActionPerformed(evt);
            }
        });

        seeBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        seeBtn.setText("View all");
        seeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeBtnActionPerformed(evt);
            }
        });

        queryBox.setViewportView(queryTF);

        javax.swing.GroupLayout bkgdLayout = new javax.swing.GroupLayout(bkgd);
        bkgd.setLayout(bkgdLayout);
        bkgdLayout.setHorizontalGroup(
            bkgdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkgdLayout.createSequentialGroup()
                .addGroup(bkgdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bkgdLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(title))
                    .addGroup(bkgdLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bkgdLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(maintxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(bkgdLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(bkgdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(queryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        bkgdLayout.setVerticalGroup(
            bkgdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkgdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(maintxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bkgdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bkgdLayout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(subBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bkgdLayout.createSequentialGroup()
                        .addComponent(queryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkgd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkgd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        new Math1().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void seeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeBtnActionPerformed
        // TODO add your handling code here:
        String query;
        File inFile;
        FileReader fr;
        BufferedReader br;

        try {
            inFile = new File("query.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);

            query = br.readLine();
            while (query != null) {
                JOptionPane.showMessageDialog(null, "Submitted querys:" + query);
                query = br.readLine();
            }
            br.close();
        } catch (IOException e) {
            System.out.println(e);

        }
        
    }//GEN-LAST:event_seeBtnActionPerformed





    private void subBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtnActionPerformed
        File outFile;
        FileWriter fw;
        BufferedWriter bw;

        String query = queryTF.getText();

        try {
            outFile = new File("query.txt");
            fw = new FileWriter(outFile, true);
            bw = new BufferedWriter(fw);

            bw.write(query);
            bw.newLine();

            bw.close();

            JOptionPane.showMessageDialog(null, "Your query has been submitted. Thank you.");
        } catch (IOException e) {
            System.out.println("Error writing to file." + e);
        }
    }//GEN-LAST:event_subBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Math3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Math3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Math3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Math3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form bkgrd */
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel bkgd;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JScrollPane maintxt;
    private javax.swing.JScrollPane queryBox;
    private javax.swing.JTextPane queryTF;
    private javax.swing.JButton seeBtn;
    private javax.swing.JButton subBtn;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
