/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/*
 *  Math23.java
 * 
 *  Rev 1
 *
 *  19/04/2013
 *
 * @author Aidan Durnin, x12388721
 *
 */
public class Math23 extends javax.swing.JFrame {

    /**
     * Creates new form Math23
     */
    public Math23() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bkg = new javax.swing.JPanel();
        mainTitle = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        mainText = new javax.swing.JLabel();
        Text = new javax.swing.JLabel();
        day = new javax.swing.JLabel();
        day2 = new javax.swing.JLabel();
        day3 = new javax.swing.JLabel();
        time3 = new javax.swing.JLabel();
        time2 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        room = new javax.swing.JLabel();
        room2 = new javax.swing.JLabel();
        room3 = new javax.swing.JLabel();
        b2wksp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bkg.setBackground(new java.awt.Color(255, 255, 255));

        mainTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mainTitle.setText("Math Workshop");

        title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        title.setText("For BAMTB1");

        mainText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mainText.setText("The following are the dates and times for the math");

        Text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Text.setText("workshops for your class:");

        day.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        day.setText("Day");

        day2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        day2.setText("Thursday");

        day3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        day3.setText("Friday");

        time3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        time3.setText("10am - 11am");

        time2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        time2.setText("10am - 11am");

        time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        time.setText("Time");

        room.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        room.setText("Room");

        room2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        room2.setText("3.02");

        room3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        room3.setText("3.08");

        b2wksp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b2wksp.setText("Back to workshop");
        b2wksp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2wkspActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bkgLayout = new javax.swing.GroupLayout(bkg);
        bkg.setLayout(bkgLayout);
        bkgLayout.setHorizontalGroup(
            bkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkgLayout.createSequentialGroup()
                .addGroup(bkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bkgLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(bkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(mainText)
                            .addComponent(Text)
                            .addComponent(title)
                            .addComponent(mainTitle)
                            .addComponent(time)
                            .addComponent(time2)
                            .addComponent(time3)))
                    .addGroup(bkgLayout.createSequentialGroup()
                        .addGroup(bkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bkgLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(day))
                            .addGroup(bkgLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(bkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bkgLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(day3))
                                    .addComponent(day2))))
                        .addGroup(bkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bkgLayout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(room))
                            .addGroup(bkgLayout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addGroup(bkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(room3)
                                    .addComponent(room2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(bkgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(b2wksp)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bkgLayout.setVerticalGroup(
            bkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTitle)
                .addGap(1, 1, 1)
                .addComponent(title)
                .addGap(1, 1, 1)
                .addComponent(mainText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Text)
                .addGap(23, 23, 23)
                .addGroup(bkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day)
                    .addComponent(time)
                    .addComponent(room))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bkgLayout.createSequentialGroup()
                        .addComponent(room2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(room3))
                    .addGroup(bkgLayout.createSequentialGroup()
                        .addGroup(bkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(time2)
                            .addComponent(day2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(day3)
                            .addComponent(time3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(b2wksp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bkg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bkg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b2wkspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2wkspActionPerformed
        // TODO add your handling code here:
        new Math2().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_b2wkspActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Math23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Math23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Math23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Math23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Math23().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text;
    private javax.swing.JButton b2wksp;
    private javax.swing.JPanel bkg;
    private javax.swing.JLabel day;
    private javax.swing.JLabel day2;
    private javax.swing.JLabel day3;
    private javax.swing.JLabel mainText;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JLabel room;
    private javax.swing.JLabel room2;
    private javax.swing.JLabel room3;
    private javax.swing.JLabel time;
    private javax.swing.JLabel time2;
    private javax.swing.JLabel time3;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
