/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


//import computing.support.SentFormPopUP;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/*
 * MeetingGUI.java
 *
 * Rev 1
 *
 * 17-4-13
 *
 * @author Kellie Hughes x12388761
 *
 */
public class MeetingGUI extends javax.swing.JFrame {

    private ArrayList<Meeting> aList;
    private String name, problem;
    private int number, count;

    /**
     * Creates new form MeetingGUI
     */
    public MeetingGUI() {
        initComponents();
        aList = new ArrayList<>();
        name = new String();
        problem = new String();
        number = 0;
        count = 0;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MeetingBackground = new javax.swing.JPanel();
        Meeting = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        StudentNumber = new javax.swing.JLabel();
        NumberTF = new javax.swing.JTextField();
        Problem = new javax.swing.JLabel();
        ProblemTF = new javax.swing.JTextField();
        Addbtn = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        Viewbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MeetingBackground.setBackground(new java.awt.Color(255, 255, 255));

        Meeting.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Meeting.setText("Organising A Meeting");

        Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Name.setText("Name:");

        NameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTFActionPerformed(evt);
            }
        });

        StudentNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StudentNumber.setText("Student Number:");

        NumberTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberTFActionPerformed(evt);
            }
        });

        Problem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Problem.setText("Problem:");

        ProblemTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProblemTFActionPerformed(evt);
            }
        });

        Addbtn.setText("Add Submission");
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NCILOGO.jpg"))); // NOI18N

        Viewbtn.setText("View Submissions");
        Viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MeetingBackgroundLayout = new javax.swing.GroupLayout(MeetingBackground);
        MeetingBackground.setLayout(MeetingBackgroundLayout);
        MeetingBackgroundLayout.setHorizontalGroup(
            MeetingBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MeetingBackgroundLayout.createSequentialGroup()
                .addGroup(MeetingBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MeetingBackgroundLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(MeetingBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MeetingBackgroundLayout.createSequentialGroup()
                                .addGroup(MeetingBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MeetingBackgroundLayout.createSequentialGroup()
                                        .addComponent(Name)
                                        .addGap(105, 105, 105))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MeetingBackgroundLayout.createSequentialGroup()
                                        .addComponent(StudentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(MeetingBackgroundLayout.createSequentialGroup()
                                        .addComponent(Problem, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(MeetingBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ProblemTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MeetingBackgroundLayout.createSequentialGroup()
                                        .addComponent(NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16))))
                            .addGroup(MeetingBackgroundLayout.createSequentialGroup()
                                .addComponent(Addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Viewbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MeetingBackgroundLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(Meeting)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        MeetingBackgroundLayout.setVerticalGroup(
            MeetingBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MeetingBackgroundLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(MeetingBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MeetingBackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Meeting)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MeetingBackgroundLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MeetingBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MeetingBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProblemTF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Problem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MeetingBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Addbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(Viewbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MeetingBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MeetingBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTFActionPerformed

    private void ProblemTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProblemTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProblemTFActionPerformed

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        name = NameTF.getText();
        problem = ProblemTF.getText();
        number = Integer.parseInt(NumberTF.getText());

        Meeting a = new Meeting();
        a.setName(name);
        a.setProblem(problem);
        a.setNumber(number);

        aList.add(a);

        count++;

        File outFile;
        FileWriter fw;
        BufferedWriter bw;

        try {
            outFile = new File("meetings.txt");
            fw = new FileWriter(outFile);
            bw = new BufferedWriter(fw);

            bw.write(name);
            bw.write(problem);
            bw.write(number);

            bw.close();
            JOptionPane.showMessageDialog(null, "You information has been submitted. Thank you.");
        } catch (IOException e) {
            System.out.println("error writing to files" + e);
        }



        // TODO add your handling code here:
       
    }//GEN-LAST:event_AddbtnActionPerformed

    private void ViewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewbtnActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < aList.size(); i++) {
            JOptionPane.showMessageDialog(null, "Name: " + aList.get(i).getName() + "        Problem: " + aList.get(i).getProblem() + "          Student Number: " + aList.get(i).getNumber());
        }
    }//GEN-LAST:event_ViewbtnActionPerformed

    private void NumberTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeetingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeetingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeetingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeetingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private javax.swing.JLabel Meeting;
    private javax.swing.JPanel MeetingBackground;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField NameTF;
    private javax.swing.JTextField NumberTF;
    private javax.swing.JLabel Problem;
    private javax.swing.JTextField ProblemTF;
    private javax.swing.JLabel StudentNumber;
    private javax.swing.JButton Viewbtn;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
