/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */




/*
 *  OnlineSupport.java
 * 
 *  Rev 1
 *
 *  17-4-13

 * @author Kellie Hughes x12388761
 *
 */
public class OnlineSupport extends javax.swing.JFrame {

    /**
     * Creates new form OnlineSupport
     */
    public OnlineSupport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Online = new javax.swing.JPanel();
        OnlineSupport = new javax.swing.JLabel();
        MoodlePara = new javax.swing.JLabel();
        Moodle = new javax.swing.JLabel();
        Citrix = new javax.swing.JLabel();
        CitrixPara = new javax.swing.JLabel();
        Library = new javax.swing.JLabel();
        LibraryPara = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Online.setBackground(new java.awt.Color(255, 255, 255));

        OnlineSupport.setBackground(new java.awt.Color(255, 255, 255));
        OnlineSupport.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        OnlineSupport.setText("Online Support");

        MoodlePara.setText("<html> Moodle (abbreviation for Modular Object Oriented Dynamic Learning Environment) is a free source e-learning sorftware platform, also known as a Learning Management System, or Virtual Learning Environment (VLE). On Moodle we have our moodle page which all of the notes and assignments available from a computer</html>");

        Moodle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Moodle.setText("Moodle:");

        Citrix.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Citrix.setText("Citrix:");

        CitrixPara.setText("<html> Citrix is a software company founded in 1989, that provides server and desktop virtualization, networking, software-as-a-service (SaaS), and cloud computing technologies, including Xen open sourse products. In simple terms it is a virtual desktop so you can get remote access to some of the software available in the college");

        Library.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Library.setText("Library:");

        LibraryPara.setText("<html> The library in the college has a service online that can make it easier to find and locate books online. It is also available so that you can hold books in your name and then go into the college and collect them. Making the library experiance so much easier.");

        back.setText("Back to main page.");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NCILOGO.jpg"))); // NOI18N

        javax.swing.GroupLayout OnlineLayout = new javax.swing.GroupLayout(Online);
        Online.setLayout(OnlineLayout);
        OnlineLayout.setHorizontalGroup(
            OnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OnlineLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(OnlineLayout.createSequentialGroup()
                .addGroup(OnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(OnlineLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(OnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Moodle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Citrix, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(MoodlePara, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                                .addComponent(CitrixPara, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGroup(OnlineLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(Library))
                        .addGroup(OnlineLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(LibraryPara, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(OnlineLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(OnlineSupport)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        OnlineLayout.setVerticalGroup(
            OnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OnlineLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(OnlineSupport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Moodle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MoodlePara, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Citrix)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CitrixPara, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Library)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LibraryPara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Online, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Online, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new LearningSupport().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OnlineSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OnlineSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OnlineSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OnlineSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new OnlineSupport().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Citrix;
    private javax.swing.JLabel CitrixPara;
    private javax.swing.JLabel Library;
    private javax.swing.JLabel LibraryPara;
    private javax.swing.JLabel Moodle;
    private javax.swing.JLabel MoodlePara;
    private javax.swing.JPanel Online;
    private javax.swing.JLabel OnlineSupport;
    private javax.swing.JButton back;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
